
# this is for MSA env. will be added before merge
server:
  port: 0
  servlet:
    context-path: /dance

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://repertory.online:8761/eureka

spring:
  application:
    name: dance
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
# for production
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://repertory.online:3306/dance?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
  jooq:
    sql-dialect: org.hibernate.dialect.H2Dialect

  data:
    mongodb:
      username: lucky
      password: turkey
      host: repertory.online
      port: 27017
      database: testdb
      authentication-database: admin

redis:
  host: repertory.online
  port: 6379

logging:
  level:
    sql: debug
    web: debug
    team.luckyturkey.danceservice: debug
    org.springframework.data.redis: debug

api:
  community:
    url: http://repertory.online:8000/community

#only for test environment
#todo: should be delete
test:
  environment:
    memberId: 1
    sourceUrl: s3//test-source-url/
    repertoryUrl: s3//test-repertory-url/

cloud:
  aws:
    s3:
      bucket: repertory
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: AKIAWHZZMWNCD6BWMOM3
      secretKey: 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
