# this is for MSA env. will be added before merge
#server:
#  port: 0
#
#spring:
#  application:
#    name: dance
#
#eureka:
#  instance:
#    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://127.0.0.1:8761/eureka

spring:

# for production
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/ssafy_web_db
#    username: root
#    password: ssafy
#  jpa:
#    hibernate:
#      ddl-auto: create
#  jooq:
#    sql-dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
  jooq:
    sql-dialect: org.hibernate.dialect.H2Dialect

server:
  servlet:
    context-path: /dance


redis:
  host: localhost
  port: 6379

logging:
  level:
    sql: debug
    web: debug
    team.luckyturkey.danceservice: debug
    org.springframework.data.redis: debug

#only for test environment
#todo: should be delete
test:
  environment:
    userId: 1
    sourceUrl: s3//testurl/