server:
#  port: 0/
  servlet:
    context-path: /member

#eureka:
#  instance:
#    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://i10a707.p.ssafy.io:8761/eureka

spring:
  profiles:
    include: oauth
  application:
    name: member
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://repertory.online:3306/member?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234


  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb # 실제 서비스시에는 바꾸기

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


redis:
  host: localhost #배포시 ec2주소 사용
  port: 6379
#  password: