server:
  port: 8000

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://i10a707.p.ssafy.io:8761/eureka

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://i10a707.p.ssafy.io'
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS
      routes:
        - id: community
          uri: lb://COMMUNITY
          predicates:
            - Path=/community/**
        - id: dance
          uri: lb://DANCE
          predicates:
            - Path=/dance/**
        - id: project
          uri: lb://PROJECT
          predicates:
            - Path=/project/**
        - id: member
          uri: lb://MEMBER
          predicates:
            - Path=/member/**