# will be used in MSA environment
server:
  port: 0
  servlet:
    context-path: /project

spring:
  application:
    name: project
  data:
    mongodb:
      uri: mongodb://lucky:turkey@repertory.online:27017/project

logging:
  level:
    org.springframework.data.mongodb: debug
    web: debug

eureka:
    instance:
        instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
        prefer-ip-address: true
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://repertory.online:8761/eureka

