# will be used in MSA environment


eureka:
    instance:
      instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
      prefer-ip-address: true
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://127.0.0.1:8761/eureka

spring:
  application:
    name: project

  data:
    mongodb:
      username: lucky
      password: turkey
      host: localhost
      port: 27017
      database: testdb
      authentication-database: admin

server:
  port: 0
  servlet:
    context-path: /project

logging:
  level:
    org.springframework.data.mongodb: debug
    web: debug

