version: "1"
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: my-jenkins
    user: root
    volumes:
      - ./jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080